package e2e

import (
	"bytes"
	"encoding/json"
	"fmt"
	"net/http"
	"net/http/httptest"
	"os"
	"os/exec"
	"path/filepath"
	"testing"
	"time"

	"github.com/agent-runner/agent-runner/internal/api"
	"github.com/agent-runner/agent-runner/internal/config"
)

type e2eEnv struct {
	server      *httptest.Server
	bareRepo    string
	reposDir string
	logsDir     string
	tmpDir      string
	mockBinDir  string
}

func setupE2E(t *testing.T) *e2eEnv {
	t.Helper()
	baseDir := t.TempDir()

	bareRepo := filepath.Join(baseDir, "origin.git")
	reposDir := filepath.Join(baseDir, "repos")
	logsDir := filepath.Join(baseDir, "logs")
	tmpDir := filepath.Join(baseDir, "tmp")
	mockBinDir := filepath.Join(baseDir, "mock-bin")

	os.MkdirAll(reposDir, 0755)
	os.MkdirAll(logsDir, 0755)
	os.MkdirAll(tmpDir, 0755)
	os.MkdirAll(mockBinDir, 0755)

	// 1. Create bare repo as "origin"
	runCmd(t, "", "git", "init", "--bare", bareRepo)

	// 2. Clone to projects dir, make initial commit, push
	projectPath := filepath.Join(reposDir, "test-project")
	runCmd(t, "", "git", "clone", bareRepo, projectPath)
	runCmd(t, projectPath, "git", "config", "user.email", "test@test.com")
	runCmd(t, projectPath, "git", "config", "user.name", "Test")

	// Create initial file and commit
	os.WriteFile(filepath.Join(projectPath, "README.md"), []byte("# Test Project\n"), 0644)
	runCmd(t, projectPath, "git", "add", "-A")
	runCmd(t, projectPath, "git", "commit", "-m", "Initial commit")
	runCmd(t, projectPath, "git", "push", "origin", "HEAD")

	// 3. Create mock claude script that writes a file and outputs JSON
	mockClaude := filepath.Join(mockBinDir, "claude")
	mockScript := `#!/bin/bash
# Write a file in the current directory
echo "// generated by claude" > generated.go
echo '{"result":"Done","cost_usd":0.01,"duration_ms":1000}'
`
	os.WriteFile(mockClaude, []byte(mockScript), 0755)

	// 4. Prepend mock dir to PATH
	os.Setenv("PATH", mockBinDir+":"+os.Getenv("PATH"))

	// 5. Create config and start server
	cfg := &config.Config{
		ReposRoot:             reposDir,
		LogsRoot:                 logsDir,
		TmpRoot:                  tmpDir,
		AllowedProjects:          []string{},
		MaxRuntimeSeconds:        30,
		MaxConcurrentJobs:        5,
		GitPushRetries:           1,
		GitPushRetryDelaySeconds: 0,
		Validation: config.ValidationConfig{
			BlockBinaryFiles: false,
			BlockedPaths:     []string{},
		},
		API: config.APIConfig{
			Bind:   "127.0.0.1:0",
			APIKey: "",
		},
		Agent: config.AgentConfig{
			MaxIterations:       50,
			MaxTotalSeconds:     60,
			MaxIterationSeconds: 30,
			Author:              "claude-agent",
			CommitPrefix:        "[agent]",
		},
		JobRetentionSeconds:     3600,
		StartupCleanupStaleJobs: false,
	}

	srv := api.NewServer(cfg)
	ts := httptest.NewServer(srv.Handler())

	return &e2eEnv{
		server:      ts,
		bareRepo:    bareRepo,
		reposDir: reposDir,
		logsDir:     logsDir,
		tmpDir:      tmpDir,
		mockBinDir:  mockBinDir,
	}
}

func runCmd(t *testing.T, dir string, name string, args ...string) string {
	t.Helper()
	cmd := exec.Command(name, args...)
	if dir != "" {
		cmd.Dir = dir
	}
	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr
	if err := cmd.Run(); err != nil {
		t.Fatalf("command %s %v failed: %v\nstdout: %s\nstderr: %s", name, args, err, stdout.String(), stderr.String())
	}
	return stdout.String()
}

func postRun(t *testing.T, serverURL string, body map[string]interface{}) (int, map[string]interface{}) {
	t.Helper()
	data, _ := json.Marshal(body)
	resp, err := http.Post(serverURL+"/run", "application/json", bytes.NewReader(data))
	if err != nil {
		t.Fatalf("POST /run failed: %v", err)
	}
	defer resp.Body.Close()

	var result map[string]interface{}
	json.NewDecoder(resp.Body).Decode(&result)
	return resp.StatusCode, result
}

func getJob(t *testing.T, serverURL, jobID string) (int, map[string]interface{}) {
	t.Helper()
	resp, err := http.Get(serverURL + "/job/" + jobID)
	if err != nil {
		t.Fatalf("GET /job failed: %v", err)
	}
	defer resp.Body.Close()

	var result map[string]interface{}
	json.NewDecoder(resp.Body).Decode(&result)
	return resp.StatusCode, result
}

func pollJobUntilDone(t *testing.T, serverURL, jobID string, timeout time.Duration) map[string]interface{} {
	t.Helper()
	deadline := time.Now().Add(timeout)
	for time.Now().Before(deadline) {
		_, result := getJob(t, serverURL, jobID)
		status, _ := result["status"].(string)
		if status == "completed" || status == "failed" {
			return result
		}
		time.Sleep(200 * time.Millisecond)
	}
	t.Fatalf("job %s did not complete within %v", jobID, timeout)
	return nil
}

func TestE2E_FullPipeline(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping E2E test in short mode")
	}

	env := setupE2E(t)
	defer env.server.Close()

	// POST /run
	code, resp := postRun(t, env.server.URL, map[string]interface{}{
		"project":     "test-project",
		"instruction": "Add generated file",
		"paths":       []string{"*.go"},
	})

	if code != http.StatusAccepted {
		t.Fatalf("expected 202, got %d: %v", code, resp)
	}

	jobID, ok := resp["job_id"].(string)
	if !ok || jobID == "" {
		t.Fatal("expected job_id in response")
	}

	// Poll until done
	result := pollJobUntilDone(t, env.server.URL, jobID, 30*time.Second)

	if result["status"] != "completed" {
		t.Fatalf("expected completed, got %s: error=%v error_code=%v",
			result["status"], result["error"], result["error_code"])
	}

	// Verify commit exists in bare repo
	cloneDir := filepath.Join(t.TempDir(), "verify")
	runCmd(t, "", "git", "clone", env.bareRepo, cloneDir)

	// Check that generated.go exists in the cloned repo
	if _, err := os.Stat(filepath.Join(cloneDir, "generated.go")); os.IsNotExist(err) {
		t.Error("expected generated.go to be pushed to origin")
	}

	// Verify run log exists
	entries, err := os.ReadDir(env.logsDir)
	if err != nil {
		t.Fatalf("failed to read runs dir: %v", err)
	}
	if len(entries) == 0 {
		t.Error("expected at least one run log file")
	}
}

func TestE2E_ValidationRejection(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping E2E test in short mode")
	}

	baseDir := t.TempDir()

	bareRepo := filepath.Join(baseDir, "origin.git")
	reposDir := filepath.Join(baseDir, "repos")
	logsDir := filepath.Join(baseDir, "logs")
	tmpDir := filepath.Join(baseDir, "tmp")
	mockBinDir := filepath.Join(baseDir, "mock-bin")

	os.MkdirAll(reposDir, 0755)
	os.MkdirAll(logsDir, 0755)
	os.MkdirAll(tmpDir, 0755)
	os.MkdirAll(mockBinDir, 0755)

	runCmd(t, "", "git", "init", "--bare", bareRepo)

	projectPath := filepath.Join(reposDir, "test-project")
	runCmd(t, "", "git", "clone", bareRepo, projectPath)
	runCmd(t, projectPath, "git", "config", "user.email", "test@test.com")
	runCmd(t, projectPath, "git", "config", "user.name", "Test")
	os.WriteFile(filepath.Join(projectPath, "README.md"), []byte("# Test\n"), 0644)
	runCmd(t, projectPath, "git", "add", "-A")
	runCmd(t, projectPath, "git", "commit", "-m", "Initial")
	runCmd(t, projectPath, "git", "push", "origin", "HEAD")

	// Mock claude writes OUTSIDE allowed paths
	mockClaude := filepath.Join(mockBinDir, "claude")
	mockScript := `#!/bin/bash
echo "unauthorized" > secret.txt
echo '{"result":"Done"}'
`
	os.WriteFile(mockClaude, []byte(mockScript), 0755)
	os.Setenv("PATH", mockBinDir+":"+os.Getenv("PATH"))

	cfg := &config.Config{
		ReposRoot:             reposDir,
		LogsRoot:                 logsDir,
		TmpRoot:                  tmpDir,
		AllowedProjects:          []string{},
		MaxRuntimeSeconds:        30,
		MaxConcurrentJobs:        5,
		GitPushRetries:           1,
		GitPushRetryDelaySeconds: 0,
		Validation: config.ValidationConfig{
			BlockBinaryFiles: false,
			BlockedPaths:     []string{},
		},
		API: config.APIConfig{
			Bind:   "127.0.0.1:0",
			APIKey: "",
		},
		Agent: config.AgentConfig{
			MaxIterations:       50,
			MaxTotalSeconds:     60,
			MaxIterationSeconds: 30,
			Author:              "claude-agent",
			CommitPrefix:        "[agent]",
		},
		JobRetentionSeconds:     3600,
		StartupCleanupStaleJobs: false,
	}

	srv := api.NewServer(cfg)
	ts := httptest.NewServer(srv.Handler())
	defer ts.Close()

	// Only allow *.go files — secret.txt should fail validation
	code, resp := postRun(t, ts.URL, map[string]interface{}{
		"project":     "test-project",
		"instruction": "Write unauthorized file",
		"paths":       []string{"*.go"},
	})

	if code != http.StatusAccepted {
		t.Fatalf("expected 202, got %d", code)
	}

	jobID := resp["job_id"].(string)
	result := pollJobUntilDone(t, ts.URL, jobID, 30*time.Second)

	if result["status"] != "failed" {
		t.Fatalf("expected failed, got %s", result["status"])
	}

	errorCode, _ := result["error_code"].(string)
	if errorCode != "PATH_VIOLATION" {
		t.Errorf("expected PATH_VIOLATION, got %s", errorCode)
	}
}

func TestE2E_ApiKeyAuth(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping E2E test in short mode")
	}

	baseDir := t.TempDir()
	reposDir := filepath.Join(baseDir, "repos")
	os.MkdirAll(reposDir, 0755)
	os.MkdirAll(filepath.Join(reposDir, "test-project", ".git"), 0755)

	cfg := &config.Config{
		ReposRoot:             reposDir,
		LogsRoot:                 filepath.Join(baseDir, "logs"),
		TmpRoot:                  filepath.Join(baseDir, "tmp"),
		AllowedProjects:          []string{},
		MaxRuntimeSeconds:        30,
		MaxConcurrentJobs:        5,
		GitPushRetries:           1,
		GitPushRetryDelaySeconds: 0,
		Validation: config.ValidationConfig{
			BlockBinaryFiles: false,
			BlockedPaths:     []string{},
		},
		API: config.APIConfig{
			Bind:   "127.0.0.1:0",
			APIKey: "secret-key-123",
		},
		Agent: config.AgentConfig{
			MaxIterations:       50,
			MaxTotalSeconds:     60,
			MaxIterationSeconds: 30,
			Author:              "claude-agent",
			CommitPrefix:        "[agent]",
		},
		JobRetentionSeconds:     3600,
		StartupCleanupStaleJobs: false,
	}

	srv := api.NewServer(cfg)
	ts := httptest.NewServer(srv.Handler())
	defer ts.Close()

	// Request without API key should fail
	body, _ := json.Marshal(map[string]interface{}{
		"project":     "test-project",
		"instruction": "do stuff",
		"paths":       []string{"src/"},
	})

	resp, err := http.Post(ts.URL+"/run", "application/json", bytes.NewReader(body))
	if err != nil {
		t.Fatalf("request failed: %v", err)
	}
	resp.Body.Close()

	if resp.StatusCode != http.StatusUnauthorized {
		t.Errorf("expected 401 without key, got %d", resp.StatusCode)
	}

	// Request with valid API key should succeed (202)
	req, _ := http.NewRequest(http.MethodPost, ts.URL+"/run", bytes.NewReader(body))
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("X-API-Key", "secret-key-123")

	resp2, err := http.DefaultClient.Do(req)
	if err != nil {
		t.Fatalf("request failed: %v", err)
	}
	resp2.Body.Close()

	if resp2.StatusCode != http.StatusAccepted {
		t.Errorf("expected 202 with valid key, got %d", resp2.StatusCode)
	}
}

func TestE2E_ProjectLocking(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping E2E test in short mode")
	}

	baseDir := t.TempDir()

	bareRepo := filepath.Join(baseDir, "origin.git")
	reposDir := filepath.Join(baseDir, "repos")
	logsDir := filepath.Join(baseDir, "logs")
	tmpDir := filepath.Join(baseDir, "tmp")
	mockBinDir := filepath.Join(baseDir, "mock-bin")

	os.MkdirAll(reposDir, 0755)
	os.MkdirAll(logsDir, 0755)
	os.MkdirAll(tmpDir, 0755)
	os.MkdirAll(mockBinDir, 0755)

	runCmd(t, "", "git", "init", "--bare", bareRepo)

	projectPath := filepath.Join(reposDir, "test-project")
	runCmd(t, "", "git", "clone", bareRepo, projectPath)
	runCmd(t, projectPath, "git", "config", "user.email", "test@test.com")
	runCmd(t, projectPath, "git", "config", "user.name", "Test")
	os.WriteFile(filepath.Join(projectPath, "README.md"), []byte("# Test\n"), 0644)
	runCmd(t, projectPath, "git", "add", "-A")
	runCmd(t, projectPath, "git", "commit", "-m", "Initial")
	runCmd(t, projectPath, "git", "push", "origin", "HEAD")

	// Mock claude that sleeps to keep the job running
	mockClaude := filepath.Join(mockBinDir, "claude")
	mockScript := fmt.Sprintf(`#!/bin/bash
sleep 5
echo "// generated" > generated.go
echo '{"result":"Done"}'
`)
	os.WriteFile(mockClaude, []byte(mockScript), 0755)
	os.Setenv("PATH", mockBinDir+":"+os.Getenv("PATH"))

	cfg := &config.Config{
		ReposRoot:             reposDir,
		LogsRoot:                 logsDir,
		TmpRoot:                  tmpDir,
		AllowedProjects:          []string{},
		MaxRuntimeSeconds:        30,
		MaxConcurrentJobs:        5,
		GitPushRetries:           1,
		GitPushRetryDelaySeconds: 0,
		Validation: config.ValidationConfig{
			BlockBinaryFiles: false,
			BlockedPaths:     []string{},
		},
		API: config.APIConfig{
			Bind:   "127.0.0.1:0",
			APIKey: "",
		},
		Agent: config.AgentConfig{
			MaxIterations:       50,
			MaxTotalSeconds:     60,
			MaxIterationSeconds: 30,
			Author:              "claude-agent",
			CommitPrefix:        "[agent]",
		},
		JobRetentionSeconds:     3600,
		StartupCleanupStaleJobs: false,
	}

	srv := api.NewServer(cfg)
	ts := httptest.NewServer(srv.Handler())
	defer ts.Close()

	// First request should succeed
	code1, _ := postRun(t, ts.URL, map[string]interface{}{
		"project":     "test-project",
		"instruction": "slow task",
		"paths":       []string{"*.go"},
	})
	if code1 != http.StatusAccepted {
		t.Fatalf("expected 202, got %d", code1)
	}

	// Give the background goroutine a moment to start
	time.Sleep(100 * time.Millisecond)

	// Second request to same project should get 409
	code2, _ := postRun(t, ts.URL, map[string]interface{}{
		"project":     "test-project",
		"instruction": "another task",
		"paths":       []string{"*.go"},
	})
	if code2 != http.StatusConflict {
		t.Errorf("expected 409 (locked), got %d", code2)
	}
}
